---
- name: Remove unused dependencies
  ansible.builtin.apt:
    autoremove: true
    purge: true

- name: Clean partial package cache
  ansible.builtin.apt:
    autoclean: true

- name: Purge full package cache
  ansible.builtin.command: apt-get clean
  changed_when: false
