---
- name: Install prerequisite packages
  ansible.builtin.apt:
    name:
      - gpg
      - apt-transport-https
      - software-properties-common
    state: present
    update_cache: true

- name: Add Grafana GPG key
  ansible.builtin.get_url:
    url: https://apt.grafana.com/gpg-full.key
    dest: /etc/apt/keyrings/grafana.asc
    mode: "0644"

- name: Add Grafana APT repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/grafana.asc] https://apt.grafana.com stable main"
    filename: grafana
    state: present
